version: '2'

services:
  frontend:
    build:
      context:  ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"

  proxy:
    build:
      context:  ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - frontend
