version: '3'

services:
  proxy:
   image: "jwilder/nginx-proxy"
   ports:
    - "80:80"
   volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  frontend:
    build:
      context:  ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=frontend.localhost

  backend:
    build:
      context:  ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=backend.localhost
